---
title: "Proyectos R - Ejercitación"
author: "Estación R"
---

## Consigna:

- Abrir el proyecto creado en clase, que contiene la base de nombres de personas. En su defecto, crear un proyecto nuevo, con una carpeta en su interior llamada `datos` y ubicar en esa carpeta la base de nombre de personas para el año 2015, vista en clase.

- Una vez en el proyecto, crear un script nuevo y en él escribir la sentencia necesaria para importar la base de nombres de personas - 2015 a nuestro Ambiente (*Environment*) de Rstudio. _Recordar guardar en un objeto esa base._

- Ejecutar las siguientes funciones sobre el data frame `base_personas` y describir con un comentario (`#`) en el script lo que realiza cada una de ellas. 

_Sugerencia:_ Intentar describir _a ojo_ lo que está haciendo la función. En caso de dificultad, consultar con el sistema de ayuda de R, anteponiendo el símbolo de cierre de interrogación (`?`) al nombre de la función. 

Ejemplo de ayuda: `?mean()`

<br>

**Ejemplo de resolución:**

```r
### dim(): Devuelve la cantidad de dimensiones del data.frame (cantidad de filas x columnas)
dim(base_personas)
```


## Lista de funciones a ejectura

| __Función__       | __Acción__ |
| :---              | :---   |
| `dim()`           | _ejecutar sobre un data frame_|
| `colnames()`      | _ejecutar sobre un data frame_|
| `str()`           | _ejecutar sobre un data frame_|
| `summary()`       | _ejecutar sobre un data frame / una columna del df_|
| `class()`         | _ejecutar sobre un data frame / una columna del df_|
| `length()`        | _ejecutar sobre un data frame / una columna del df_|
| `table()`         | _ejecutar sobre una columna del df_|
| `is.na()`         | _ejecutar sobre una columna del df_|
| `mean()`          | _ejecutar sobre una columna del df_|
